name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: my-cicd-project:latest

    - name: List Docker images
      run: docker images

    - name: Verify Docker image
      run: docker inspect my-cicd-project:latest

    - name: Run Docker container
      run: docker run -d -p 5000:5000 my-cicd-project:latest
